[package]
name = "xlsx_to_json"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "0.18.0"
serde_json = "1.0.79"
serde = "1.0.136"
serde_derive = "1.0.136"
differ = "1.0.3"